trigger:
- none

pool:
  name: lab

variables:
- group: Packer

steps:
- script: |
    packer init .
    packer build -var "ssh_password=$(ssh_root_password)" .
  displayName: 'Build Image'

- script: |
    vagrant box add rocky_linux ./rocky_linux_virtualbox.box
  displayName: 'Push vagrant box'