trigger:
- none

pool:
  name: lab

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: packer build vm.pkr.hcl
  displayName: 'Build Image'

- script: |
    FILES=$(find . -name "*.vmdk")
    echo "Path to fille: $FILES"
    echo "##vso[task.setvariable variable=vmdk_image_path]$FILES"
  displayName: 'Get vmdk'
  
- script: |
    echo "VMDK path: $(vmdk_image_path)"
    terraform providers
    terraform init
    terraform plan -var="vmdk_image_path=$(vmdk_image_path)"
    terraform apply -auto-approve -var="vmdk_image_path=$(vmdk_image_path)"
  displayName: 'Run Terraform'