trigger:
- none

pool:
  name: lab

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: packer build vm.pkr.hcl
  displayName: 'Build Image'

- script: |
    FILES=$(find . -name "*.ovf")
    echo "Path to fille: $FILES"
    echo "##vso[task.setvariable variable=ovf_image_path]$FILES"
  displayName: 'Get vmdk'
  
- script: |
    echo "VMDK path: $(ovf_image_path)"
    terraform providers
    terraform init
    terraform plan -var="vmdk_image_path=$(ovf_image_path)" -out=plan.tfplan
    terraform apply -auto-approve plan.tfplan 
  displayName: 'Run Terraform'